name: 'Check recent commits'
description: 'check if there are commits for the duration specified'
inputs:
  repo:
    description: 'repo'
    required: true
    default: ${{ github.repository }}
  token:
    description: 'access token'
    required: true
    default: ${{ github.token }}
  days-since:
    description: 'check commits since number of days'
    required: true
    default: '1'
  path:
    description: 'check for commits under this path'
    required: false
    default: ''
outputs:
  has-commits:
    description: "repo has commits"
    value: ${{ steps.check-commits.outputs.has-commits }}
runs:
  using: "composite"
  steps:
    - id: check-commits
      env:
        INPUT_REPO: ${{ inputs.repo }}
        INPUT_DAYS: ${{ inputs.days-since }}
        INPUT_TOKEN: ${{ inputs.token }}
        INPUT_PATH: ${{ inputs.path }}
      run: ${{ github.action_path }}/check-commits-since.sh
      shell: bash
